.Dd February 8, 2015
.Dt NSRLSVR 1
.Os
.Sh NAME
.Nm nsrlsvr
.Nd server yielding hashes from NIST's NSRL RDS
.Sh SYNOPSIS
.Nm nsrlsvr
.Op Fl b
.Op Fl h
.Op Fl v
.Op Fl f Ar hash-file
.Op Fl p Ar port
.Sh DESCRIPTION
nsrlsvr provides a daemon that services queries from clients requesting information
about whether certain hash values are present in the NIST National Software Reference
Laboratory Reference Data Set (NSRL RDS).
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl b
show information on submitting bug reports, then exit
.It Fl h
show a help screen, then exit
.It Fl v
show version information, then exit
.It Fl f Ar hash-file
specify an alternate hash file in
.Ar hash-file
.It Fl p Ar port
listen on port (default: 9120)
.Ar port
.El
.Sh NOTES
To support the full NSRL RDS requires a lot of memory.  Although it will run on
a 4Gb system, the results may be unsatisfactory.  A 64-bit OS with at least 8Gb
of RAM is recommended.
.Pp
.Sh BUGS
None known.
.Sh SEE ALSO
nsrllookup(1)
.Sh AUTHOR
Robert J. Hansen <rjh@secret-alchemy.com>
